name: C++ validation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install native dependencies
        run: sudo apt-get update && sudo apt-get install -y ninja-build libssl-dev zlib1g-dev
      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        run: cmake --build build --verbose
      - name: Test
        run: ctest --test-dir build --output-on-failure
